server:
  port: 8080
spring:
  application:
    name: "test-software-engineer"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapter:
  restconsumer:
    timeout: 5000
    url: "http://dummy.restapiexample.com/api/v1"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
